#!/usr/bin/env bash

INTERMEDIATE_DIR="generated-intermediates"

function file_sz() {
    if [ "$(uname -s)" == "Darwin" ]; then
        echo $(stat -f %z $1)
    else
        echo $(stat -c %s $1)
    fi
}

function os_sym_prefix() {
    if [ "$(uname -s)" == "Darwin" ]; then
        echo '_'
    else
        echo ''
    fi
}

function gen_asm() {
    local BIN_F=$1
    local SZ=$(file_sz $BIN_F)
    local NAME=$(basename $BIN_F | cut -f 1 -d '.')
    local PREFIX="$(os_sym_prefix)"

    echo ".global ${PREFIX}const_${NAME}"
    echo ".global ${PREFIX}const_${NAME}_end"
    echo ".global ${PREFIX}const_${NAME}_sz"
    echo "${PREFIX}const_${NAME}:"
    echo ".incbin \"$BIN_F\""
    echo "${PREFIX}const_${NAME}_end:"
    echo "${PREFIX}const_${NAME}_sz:"
    echo ".int $SZ"
}

if [ "$1" = "" ]; then
    echo "error: no input"
    exit 1
fi

if ! [ -f "$1" ]; then
    echo "error: input file missing"
    exit 1
fi

if [ "$2" = "" ]; then
    echo "error: no output"
    exit 1
fi

if [ -f "$2" ]; then
    rm -f $2
fi

if ! [ -d "$INTERMEDIATE_DIR" ]; then
    mkdir $INTERMEDIATE_DIR
fi

if [ "$CC" = "" ]; then
    CC=clang
fi

NAME=$(basename $1 | cut -f 1 -d '.')
INTERMEDIATE="$INTERMEDIATE_DIR/$NAME.S"

if [ -f "$INTERMEDIATE" ]; then
    rm -f "$INTERMEDIATE"
fi

gen_asm $1 >> $INTERMEDIATE
$CC $INTERMEDIATE -c -o "$2" $3
